### PR TITLE
Add a comboBox to choose the current layout

### PR DESCRIPTION
**Pull request by matthieuheitz**
In InteractiveSegmentTubes module
See Issue #36

### CODE REVIEW

**Comment by vovythevov** [comment]
Did you think about the following case: the user opens opens this module,
selects the red view. Then a module that has a red view (not the default).
Then selects this module again.
Would the red view be selected ? Because the user would probably expect it
:)

On Tuesday, February 10, 2015, Matthieu Heitz <notifications@github.com>
wrote:

> In InteractiveSegmentTubes module
> See Issue #36 <https://github.com/KitwareMedical/VesselView/issues/36>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/KitwareMedical/VesselView/pull/81
> Commit Summary
>
>    - Add a comboBox to choose the current layout
>
> File Changes
>
>    - *M*
>    Modules/Scripted/InteractiveSegmentTubes/InteractiveSegmentTubesWidget/InteractiveSegmentTubesWidget.py
>    <https://github.com/KitwareMedical/VesselView/pull/81/files#diff-0>
>    (33)
>    - *M*
>    Modules/Scripted/InteractiveSegmentTubes/Resources/UI/InteractiveSegmentTubes.ui
>    <https://github.com/KitwareMedical/VesselView/pull/81/files#diff-1>
>    (107)
>
> Patch Links:
>
>    - https://github.com/KitwareMedical/VesselView/pull/81.patch
>    - https://github.com/KitwareMedical/VesselView/pull/81.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KitwareMedical/VesselView/pull/81>.
>


-- 
Sent from Gmail Mobile

**Comment by matthieuheitz** [comment]
Should it be Red because you come from another module that had a Red View, or because last time you left this module, it had a Red View.
Example: If I go in InteractiveSegmentTubes, select the Green slice. Then, I go to another module where the Red slice is the layout. When I go back to InteractiveSegmentTubes, should the layout be Red or Green ? (or default, aka Quad View)

**Comment by matthieuheitz** [comment]
I don't populate a list anymore since I only look for one value. Instead, I use findText()
And I saw with Stephen, for now, we keep the behavior of always going back to the default layout = Quad View.

**Comment by matthieuheitz** [comment]
@jcfr can you review ?

**Comment by matthieuheitz** [comment]
Updated ! Thank you @jcfr , it's much cleaner.

**Comment by matthieuheitz** [comment]
Re-updated

**Comment by matthieuheitz** [comment]
Updated again

**Comment by matthieuheitz** [comment]
@jcfr can you review please ?

**Pull request merged**
