### PR TITLE
Add a VesselView style plugin and set it as default

### PR DESCRIPTION
**Pull request by matthieuheitz**
Also corrected a typo in the welcome paragraph
See Issue #66, and #83

### CODE REVIEW

**Comment by jcfr** [comment]
Beside of the small details, LGTM

[LGTM](http://www.lgtm.in/i/M4MWhgz8q)

[:+1:](http://www.lgtm.in/u/M4MWhgz8q) [:-1:](http://www.lgtm.in/r/M4MWhgz8q)

**Comment by matthieuheitz** [comment]
You're right, I'll change it.
Note that the inconsistency is also in Slicer :)
https://github.com/Slicer/Slicer/blob/master/Base/QTGUI/StylePlugins/CMakeLists.txt#L9

**Comment by matthieuheitz** [comment]
Updated !

**Comment by jcfr** [comment]
> Note that the inconsistency is also in Slicer :)

Thanks for reporting this.

After you confirm it compiles (make sure to delete the generated header file in the build tree) .. lgtm.

**Comment by matthieuheitz** [comment]
It compiles and runs great :)

**Comment by matthieuheitz** [comment]
Actually wait, there are some weird stuff. I'm gonna do a clean build.

**Comment by matthieuheitz** [comment]
All right ! The clean build works :+1:

**Pull request merged**
